name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: swift build
      - name: Tests
        run: swift test --enable-code-coverage
      - name: Codecov
        run: |
          llvm-cov export -format="lcov" .build/debug/ValidationToolkitPackageTests.xctest/Contents/MacOS/ValidationToolkitPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/ValidationToolkitPackageTests.lcov
          bash <(curl https://codecov.io/bash)
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
